import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Stringify</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to Stringify!
        </h1>
        <div className={styles.grid}>
          <Link href='/Clients'>
            <a className={styles.card}>
              <h2>Clients &rarr;</h2>
              <p>Create and manage client's requests and information</p>
            </a>
          </Link>

          <Link href='/StringJobs'>
            <a className={styles.card}>
              <h2>String Jobs &rarr;</h2>
              <p>Create and view detailed information about string jobs</p>
            </a>
          </Link>
        </div>
      </main>
    </div>
  )
}

export default Home
